module.exports.descriptors = [
    'Sacred',
    'Misty',
    'Verdant',
    'Ancient',
    'Enchanted',
    'Sunset',
    'Moonlit',
    'Jungle',
    'Cascading',
    'Emerald',
    'Golden',
    'Silent',
    'Serene',
    'Himalayan',
    'Desert',
    'Mangrove',
    'Coastal',
    'Majestic',
    'Tribal',
    'Mystic'
];

module.exports.places= [
    'Meadow',
    'Ghat',
    'Valley',
    'Dunes',
    'Mangroves',
    'Hillside',
    'Backwaters',
    'Tea Estate',
    'Forest Camp',
    'Riverbank',
    'Coconut Grove',
    'Island Camp',
    'Sanctuary',
    'Jungle Retreat',
    'Cliffside',
    'Plateau',
    'Wildlife Reserve',
    'Temple View',
    'Lake Camp',
    'Cave Retreat'
];
